# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Foo" do
    optional :name, :string, 1
    optional :id, :uint64, 2
  end
  add_message "FooRequest" do
    optional :name, :string, 1
  end
  add_message "FooResponse" do
    optional :foos, :message, 1, "Foo"
  end
end

Foo = Google::Protobuf::DescriptorPool.generated_pool.lookup("Foo").msgclass
FooRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("FooRequest").msgclass
FooResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("FooResponse").msgclass
